from flask import Flask, render_template, request

app = Flask(__name__)

medicaments = {
    "acebutolol": "Monitan",
    "acetazolamide": "Diamox",
    "alendronate tablet": "Fosamax",
    "acyclovir capsule": "Zovirax",
    "alendronate": "Fosamax",
    "alfuzosin hcl": "Xatral",
    "allernix": "Benadryl",
    "allopurinol tablet": "Zyloprim",
    "almotriptan": "Axert",
    "alprazolam": "Xanax",
    "amantadine": "Symmetrel",
    "amiodarone tablet": "Cordarone",
    "amitriptyline tablet": "Elavil",
    "amlodipine besylate": "Norvasc",
    "amoxicilline": "Amoxil",
    "amoxi-clav": "Clavulin",
    "anastrozole": "Arimidex",
    "apixaban": "Eliquis",
    "aripiprazole": "Abilify",
    "ASA EC tablet": "Aspirin EC Tablet",
    "atenolol tablet": "Tenormin",
    "atenolol/chlorthalidone tablet": "Tenoretic",
    "atorvastatin calcium": "Lipitor",
    "azathioprine": "Imuran (dangereux)",
    "azithromycine": "Zithromax",
    "baclofen tablet": "Lioresal",
    "benazepril tablet": "Lotensin",
    "benztropine tablet": "Cogentin",
    "betahistine": "Serc",
    "bicalutamide": "Casodex",
    "bisoprolol": "Monocor",
    "bromazepam": "Lectropram",
    "bromocriptine": "Parlodel",
    "bupropion hcl": "Wellbutrin SR / XL",
    "buspirone tablet": "Buspar",
    "calcitriol capsule": "Rocaltrol",
    "candesartan cilexetil-hydrochlorothiazide": "Atacand HCT",
    "candesartan cilexetil": "Atacand",
    "captopril tablet": "Capoten",
    "carbamazepine tablet": "Tegretol",
    "carbidopa/levodopa SR tablet": "Sinemet CR",
    "carbidopa/levodopa tablet": "Sinemet",
    "carvedilol": "Coreg",
    "cefadroxil": "Duricef",
    "cefixime": "Suprax",
    "cefprozil": "Cefzil",
    "cefuroxime": "Ceftin",
    "cephalexine": "Keflex",
    "chlorpromazine HCL": "Largactil",
    "chlorthalidone tablet": "Hygroton",
    "cholestyramine": "Olestyr",
    "ciprofloxacin": "Cipro",
    "citalopram tablet": "Celexa",
    "clarithromycine": "Biaxin",
    "clindamycin": "Dalacin",
    "clomipramine hcl": "Anafranil",
    "clonazepam tablet": "Rivotril (dangereux)",
    "clonidine HCL tablets": "Catapres",
    "clopidogrel bisulfate tablets": "Plavix",
    "clotrimazole/betamethasone cream": "Lotriderm",
    "cyclobenzaprine": "Flexeril",
    "dapagliflozine": "Forxiga",
    "desmopressine": "DDAVP",
    "desvenlafaxine": "Pristiq",
    "dextroamphetamine-amphetamine ER": "Adderall XR",
    "dextroamphetamine-amphetamine": "Dexedrine",
    "diazepam tablet": "Valium",
    "diclofenac EC tablet": "Voltaren",
    "dicyclomine capsule": "Bentylol",
    "digoxin tablets": "Lanoxin",
    "diltiazem ER capsule": "Tiazac",
    "diltiazem CD": "Cardizem CD",
    "divalproex tablet": "Epival (dangereux)",
    "docusate sodium": "Colace",
    "domperidone": "Motilium",
    "donepezil HCI": "Aricept",
    "dorzolamide HCL": "Trusopt",
    "doxazosin mesylate": "Cardura",
    "doxepin capsule": "Sinequan",
    "doxycycline": "Vibramycin",
    "duloxetine": "Cymbalta",
    "dutasteride": "Avodart (dangereux)",
    "eletriptan": "Relpax",
    "enalapril maleate": "Vasotec",
    "enalapril/HCTZ": "Vaseretic",
    "epinephrine auto injector": "EpiPen",
    "eplerenone tablet": "Inspra",
    "escitalopram oxalate": "Cipralex",
    "esomeprazole DR capsule": "Nexium",
    "estradiol tablet": "Estrace (dangereux)",
    "eszopiclone": "Lunesta",
    "ezetimibe": "Ezetrol",
    "etodolac tablet": "Lodine",
    "famciclovir": "Famvir",
    "famotidine tablet": "Pepcid",
    "felodipine ER tablet": "Plendil ER",
    "fenofibrate": "Tricor / Lipidil",
    "ferrous sulfate EC tablet": "Ferrous Sulfate",
    "fesoterodine fumarate": "Toviaz",
    "finasteride tablet": "Proscar",
    "flecainide acetate tablet": "Tambocor",
    "fluconazole": "Diflucan",
    "fluoxetine capsule": "Prozac",
    "fluticasone nasal spray": "Flonase",
    "fluvoxamine maleate tablet": "Luvox",
    "fosfomycin": "Monurol",
    "fosinopril": "Monopril",
    "furosemide tablet": "Lasix",
    "gabapentin": "Neurontin",
    "gemfibrozil": "Lopid",
    "glimepiride": "Amaryl",
    "glyburide tablet": "Diabeta",
    "guanfacine": "Intuniv",
    "haloperidol tablet": "Haldol",
    "hydralazine tablet": "Apresoline",
    "hydrochlorothiazide": "Hydrodiuril",
    "hydrocortisone tablet": "Cortef",
    "hydromorphone": "Dilaudid",
    "hydroxychloroquine": "Plaquenil",
    "hydroxyzine HCL tablet": "Atarax",
    "ibuprofen tablet": "Advil / Motrin",
    "imipramine": "Tofranil",
    "indapamide tablet": "Lozide",
    "indomethacin": "Indocid",
    "irbesartan": "Avapro",
    "irbesartan/HCTZ": "Avalide",
    "isosorbide mononitrate": "Imdur",
    "labetalol HCL tablet": "Trandate",
    "lacosamide": "Vimpat",
    "lamotrigine": "Lamictal",
    "lansoprazole DR capsule": "Prevacid",
    "latanoprost": "Xalatan",
    "letrozole": "Femara (dangereux)",
    "levetiracetam tablet": "Keppra",
    "levothyroxine": "Synthroid",
    "liothyronine sodium": "Cytomel",
    "lisinopril": "Prinivil / Zestril",
    "lisinopril/HCTZ": "Zestoretic",
    "lithium carbonate": "Carbolith",
    "loperamide capsule": "Imodium",
    "loratadine": "Claritin OTC",
    "lorazepam tablet": "Ativan",
    "losartan potassium": "Cozaar",
    "losartan/HCTZ": "Hyzaar",
    "lovastatin tablet": "Mevacor",
    "meloxicam": "Mobicox",
    "metformin": "Glucophage",
    "metformin XR": "Glucophage XR",
    "methimazole tablets": "Tapazole",
    "methocarbamol tablet": "Robaxin",
    "methotrexate": "Methotrexate",
    "methylphenidate": "Ritalin / Concerta / Biphentin",
    "metoclopramide HCL tablet": "Maxeran",
    "metolazone tablet": "Zaroxolyn",
    "metoprolol tartrate tablet": "Lopresor",
    "midodrine HCL tablet": "Amatine",
    "minocycline capsule": "Minocin",
    "mirtazapine tablet": "Remeron",
    "mometasone furoate": "Elocom",
    "montelukast sodium": "Singulair",
    "moxifloxacin": "Avelox",
    "mycophenolate mofetil": "CellCept",
    "naltrexone": "Revia",
    "naproxen": "Anaprox / Naprosyn",
    "niacin": "Niacin",
    "nifedipine capsule": "Adalat",
    "nitrofurantoin": "Macrobid",
    "nortriptyline HCL capsule": "Aventyl",
    "olanzapine": "Zyprexa",
    "olmesartan": "Olmetec",
    "omeprazole capsule": "Losec",
    "ondansetron": "Zofran",
    "oxazepam": "Serax",
    "oxybutynin tablet": "Ditropan",
    "oxycodone": "Supeudol",
    "pantoprazole sodium": "Pantoloc",
    "paroxetine HCL tablet": "Paxil",
    "perindopril": "Coversyl",
    "phenytoin sodium capsule": "Dilantin (dangereux)",
    "potassium chloride ER tablet": "K-Dur",
    "pramipexole": "Mirapex",
    "pravastatin tablet": "Pravachol",
    "prazosin capsule": "Minipress",
    "prednisone": "Prednisone",
    "pregabalin": "Lyrica",
    "propranolol": "Inderal",
    "quetiapine fumarate": "Seroquel",
    "ramipril": "Altace",
    "ranitidine": "Zantac",
    "rivaroxaban": "Xarelto",
    "rosuvastatin calcium": "Crestor",
    "sertraline HCI": "Zoloft",
    "simvastatin tablets": "Zocor",
    "spironolactone": "Aldactone (dangereux)",
    "sumatriptan": "Imitrex",
    "tamsulosin hydrochloride": "Flomax",
    "telmisartan": "Micardis",
    "temazepam capsule": "Restoril",
    "trazodone tablet": "Desyrel",
    "tramadol": "Ultram",
    "valacyclovir HCL tablet": "Valtrex",
    "valproic acid": "Depakene",
    "valsartan": "Diovan",
    "venlafaxine": "Effexor",
    "verapamil": "Isoptin",
    "warfarin sodium": "Coumadin (dangereux)",
    "zolpidem": "Sublinox",
    "zopiclone": "Imovane"
}

@app.route("/", methods=["GET", "POST"])
def home():
    resultats = []

    if request.method == "POST":
        recherche = request.form["recherche"].lower()

        for g, c in medicaments.items():
            if g.startswith(recherche) or c.lower().startswith(recherche):
                resultats.append(f"{g} → {c}")

    return render_template("index.html", resultats=resultats)

if __name__ == "__main__":
    app.run(debug=True)